# .github/workflows/build.yml
name: Build Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t my-image:latest .
          docker save -o my-image.tar my-image:latest
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-image.tar
